using System.Text.Json.Serialization;

namespace SolScanner;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum EActivityType
{
    ACTIVITY_SPL_TRANSFER, ACTIVITY_SPL_BURN, ACTIVITY_SPL_MINT, ACTIVITY_SPL_CREATE_ACCOUNT
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum EDefiActivityType
{
    ACTIVITY_TOKEN_SWAP, ACTIVITY_AGG_TOKEN_SWAP, ACTIVITY_TOKEN_ADD_LIQ, ACTIVITY_TOKEN_REMOVE_LIQ, ACTIVITY_SPL_TOKEN_STAKE, ACTIVITY_SPL_TOKEN_UNSTAKE, ACTIVITY_SPL_TOKEN_WITHDRAW_STAKE, ACTIVITY_SPL_INIT_MINT
}