name: Nuget Push

# Trigger workflow on pushes to main or pull requests into main
on:
  workflow_dispatch:
    # all inputs default to push all - if package exists already, it'll be skipped anyway
    inputs:
      publishMain:
        description: 'Publish SolScanner from main (Y/N)?'
        required: true
        default: 'Y'

jobs:
  nuget-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
        
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build SolScanner
        run: dotnet build ./src/SolScanner -c Release
        
      - name: Pack SolScanner
        run: dotnet pack -c Release --no-build --output .
        
      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json